name: "fgbio SetMateInformation"
description:
  Adds and/or fixes mate information on paired-end reads. Sets the
  MQ (mate mapping quality), MC (mate cigar string), ensures all mate-related
  flag fields are set correctly, and that the mate reference and mate start
  position are correct.
authors:
  - Patrik Smeds
